### PR TITLE
[PyTorch] Add Multiple GPUs Scratch

### PR DESCRIPTION
**Pull request by AnirudhDagar**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by AnirudhDagar** [comment]
Jenkins is probably stuck.

**Comment by mli** [comment]
Job d2l-en/PR-1596/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1596/

**Comment by mli** [comment]
Job d2l-en/PR-1596/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1596/

**Comment by mli** [comment]
Job d2l-en/PR-1596/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1596/

**Comment by mli** [comment]
Job d2l-en/PR-1596/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1596/

**Comment by astonzhang** [comment]
Thanks. Due to the change of `sgd` and `evaluate_accuracy_gpu`, I'll merge it first then test all the notebooks

**Pull request merged**
