### PR TITLE
refactor code in chapter mlp

### PR DESCRIPTION
**Pull request by mli**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1872/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1872/

**Comment by astonzhang** [comment]
Thanks. Our CI is pending this PR (e.g., underfit-overfit needs to be refactored because `d2l. train_epoch_ch3` is no longer available due to https://github.com/d2l-ai/d2l-en/commit/57237b0dd5def2f500b8e6567f29a1badb445995): 
http://ci.d2l.ai/blue/organizations/jenkins/d2l-en/detail/master/1051/pipeline

**Comment by mli** [comment]
Job d2l-en/PR-1872/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1872/

**Comment by mli** [comment]
Job d2l-en/PR-1872/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1872/

**Pull request merged**
