### PR TITLE
Clarify LeNet Exercise

### PR DESCRIPTION
**Pull request by goldmermaid**

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1472/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1472/

**Comment by astonzhang** [comment]
We consistently refer to "activations", which is defined in https://d2l.ai/chapter_multilayer-perceptrons/mlp.html
"The outputs of activation functions (e.g.,  𝜎(⋅) ) are called activations."

**Comment by goldmermaid** [comment]
A lot of students won't read the precious chapters/sections, so they may feel confused (such as this one: https://discuss.d2l.ai/t/convolutional-neural-networks-lenet/73/3).

**Comment by astonzhang** [comment]
"activations" are an important concept and they are frequently used throughout the book. We cannot redefine it every time they appear. In this case, help on the forum is useful.

**Pull request closed without merging**
