### PR TITLE
[WIP][pytorch] add Image aug

### PR DESCRIPTION
**Pull request by StevenJokess**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by StevenJokess** [comment]
https://github.com/StevenJokess/d2l-en-read/blob/master/Ch13_CV/13_1pt.ipynb

**Comment by mli** [comment]
Job d2l-en/PR-1456/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1456/

**Comment by StevenJokess** [comment]
@mli @astonzhang 
There are not enough 40 notebooks left...
And the difficulty of last chapter(
http://preview.d2l.ai/d2l-en/master/chapter_generative-adversarial-networks/gan.html
http://preview.d2l.ai/d2l-en/master/chapter_generative-adversarial-networks/dcgan.html)
is more challenging than others in general. It is more like a real project.

Besides,
I have 
1. fixed lots of typo (something like "title = Dive into Deep Learing")
2. added helpful discussions 
(https://discuss.d2l.ai/t/do-these-before-you-ask/540/5 
https://discuss.d2l.ai/t/using-jupyter/421/2
...
Too many
You have time to **look through** the whole book's discussion then you will find that I am not bullshiting...)
image
image
image
3. 20+ issues(all disappear... You should take attention before.)
4. replied a lot of questions.
5. share my reading repo: https://github.com/StevenJokess/d2l-en-read

You can find some contributions: https://github.com/dltech-xyz/d2l-en-read/tree/master/My%20contribution
image

I'm hunting a job to start AI.(I survive just for AI. Now I can't find any meaning for my life.)
It is really important for my whole life.
I don't have a famous or master degree to prove.
It is all I have.
Please help me...

**Comment by astonzhang** [comment]
We have been quite clear in our earlier conversations. To reiterate, please stay relevant in PR/Issues and do not post irrelevant topics as it may spam others' inboxes.

**Pull request closed without merging**
