### PR TITLE
Remove the pinned cloudpickle version

### PR DESCRIPTION
**Pull request by terrytangyuan**
*Description of changes:*

Now that https://github.com/tensorflow/probability/issues/991 has been fixed so things should work as expected.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by astonzhang** [comment]
Can you rebase to master HEAD to pass the ci?

**Comment by terrytangyuan** [comment]
Rebased but seems like master is failing now.

**Comment by mli** [comment]
Job d2l-en/PR-1275/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1275/

**Comment by astonzhang** [comment]
Fixed CI, now it passes.

**Pull request merged**
