### PR TITLE
[Do not merge] Release v0.16

### PR DESCRIPTION
**Pull request by astonzhang**
v0.16 is a milestone release featuring a brand-new attention chapter and completion of PyTorch adaptation for Vol.1.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by AnirudhDagar** [comment]
@terrytangyuan can you please take a look at [this](http://ci.d2l.ai/blue/organizations/jenkins/d2l-en/detail/PR-1603/1/pipeline) assertion error on the tensorflow port?

**Comment by terrytangyuan** [comment]
Can we re-trigger the build? It might be the known flaky issue that we encountered before.

**Comment by AnirudhDagar** [comment]
CI should re-run now

**Comment by mli** [comment]
Job d2l-en/PR-1603/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1603/

**Comment by mli** [comment]
Job d2l-en/PR-1603/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1603/

**Comment by mli** [comment]
Job d2l-en/PR-1603/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1603/

**Comment by mli** [comment]
Job d2l-en/PR-1603/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1603/

**Comment by mli** [comment]
Job d2l-en/PR-1603/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1603/

**Comment by mli** [comment]
Job d2l-en/PR-1603/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1603/

**Comment by mli** [comment]
Job d2l-en/PR-1603/8 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1603/

**Comment by mli** [comment]
Job d2l-en/PR-1603/10 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1603/

**Comment by mli** [comment]
Job d2l-en/PR-1603/11 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1603/

**Comment by mli** [comment]
Job d2l-en/PR-1603/13 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1603/

**Comment by mli** [comment]
Job d2l-en/PR-1603/14 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1603/

**Pull request merged**
