### PR TITLE
handling path building in xplatform manner + some minor issues and typos

### PR DESCRIPTION
**Pull request by IgorDzreyev**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by astonzhang** [comment]
Can you resolve the conflicts by removing (object)?

**Comment by IgorDzreyev** [comment]
> Can you resolve the conflicts by removing (object)?
Looks like it is done...

**Comment by astonzhang** [comment]
Thanks!
A minor suggestion is that, you may wish to install an nbextension called ruler to ensure that each line in the code cell does not exceed 78 chars:
https://d2l.ai/chapter_appendix-tools-for-deep-learning/jupyter.html#timing

**Comment by astonzhang** [comment]
Regarding your change:

natural-language-inference-and-dataset.md
        s = re.sub('\(', '', s) 
        s = re.sub('\)', '', s)
->
        s = re.sub('\\(', '', s) 
        s = re.sub('\\)', '', s)

        s = re.sub('\s{2,}', ' ', s)
->
        s = re.sub('\\s{2,}', ' ', s)

For input
s = '( ( ( A person ) ( on ( a horse ) ) ) ( ( jumps ( over ( a ( broken ( down airplane ) ) ) ) ) . ) )'

both correctly return
'A person on a horse jumps over a broken down airplane .'

Is there any reason why \\ is preferred over \?

**Comment by IgorDzreyev** [comment]
Well, I've noticed this with help of PyCharm.

Here is what Official Python Docs says (https://docs.python.org/3.8/library/re.html):

...
Regular expressions use the backslash character ('\') to indicate special forms or to allow special characters to be used without invoking their special meaning. This collides with Python’s usage of the same character for the same purpose in string literals; for example, to match a literal backslash, one might have to write '\\\\' as the pattern string, because the regular expression must be \\, and each backslash must be expressed as \\ inside a regular Python string literal. Also, please note that any invalid escape sequences in Python’s usage of the backslash in string literals now generate a DeprecationWarning and in the future this will become a SyntaxError. This behaviour will happen even if it is a valid escape sequence for a regular expression.
...

**Comment by astonzhang** [comment]
Thanks. Besides, after your changes in `download_extract`, we also need to make some more changes:
https://github.com/d2l-ai/d2l-en/commit/50ad5dea5e4edb95193cd55ee8928d8c841da294
https://github.com/d2l-ai/d2l-en/commit/93de46ee9bedd46bdc4dc68d9f6845342a69835c

to pass the entire book. This is due to the fact that d2l.download_extract will be invoked by many other notebooks, thus changes of anything inside d2l.py needs to be evaluated throughout the entire book. Unfortunately, CI only tests your modified files thus misses to report errors in other affected notebooks.

To test changes that potentially affect the entire book, you may 

1. `pip install d2lbook`
1. `cd d2l-en && python setup.py develop  # So any changes in d2l/d2l.py will take effect`
1. `d2lbook build lib  # Copy changes in d2l functions from md source to d2l/d2l.py`
1.   In config.ini, set `force_eval_entire_book = True`
1. `d2lbook build eval  # Test the entire book`
1. If the entire book passes, `git checkout -- config.ini`

**Comment by IgorDzreyev** [comment]
Yes, I've tried to build it all locally, but there is an issue with multiple GPU chapter - it requires 2 GPUs...

**Comment by IgorDzreyev** [comment]
Regarding d2l.py - Isn't it build from chapters' code?

**Comment by IgorDzreyev** [comment]
'...Unfortunately, CI only tests your modified files thus misses to report errors in other affected notebooks...' - after I've made first commit and couple after - CI failed in different places I didn't touch, so it looks like it checks all the code after all - those changes with "import os" were for that

**Comment by IgorDzreyev** [comment]
"d2lbook build eval" just converts .md-s to .ipynb-s... it there a command in d2lbook to actually execute all notebooks?

**Comment by astonzhang** [comment]
> Regarding d2l.py - Isn't it build from chapters' code?

yes, but you need to explicitly `d2lbook build lib` to copy from source to lib




> "d2lbook build eval" just converts .md-s to .ipynb-s... it there a command in d2lbook to actually execute all notebooks?

https://github.com/d2l-ai/d2l-en/blob/master/config.ini#L35
should be True

**Comment by astonzhang** [comment]
regarding those 2 GPU requirement, you may exclude them in your eval
https://github.com/d2l-ai/d2l-en/blob/master/config.ini#L32

**Comment by IgorDzreyev** [comment]
Cool, thanks for clarifying!
By any chance - is there "-j option" for parallel evaluation? )

**Comment by astonzhang** [comment]
that's a nice idea! I think maybe I can support that feature by using Python multiprocessing. Do you have any suggestions?

**Comment by IgorDzreyev** [comment]
Well, I didn't have a change to look into d2lbook code thoroughly...

**Comment by IgorDzreyev** [comment]
https://github.com/d2l-ai/d2l-book/blob/a75585d41f7fb6e39866783fd65bfa6b7116e4c2/d2lbook/build.py#L427 ?

**Comment by IgorDzreyev** [comment]
Hmm... Some of notepads loads GPU at top. So it can be an issue when running them simultaneously... They will fail with 'Out of (GPU) RAM'...

On the other hand - there is not much of them, so they may be treated separately - serialized, at the end of evaluation, for example.

But the question - will it be worth of maintaining all this stuff...

**Comment by IgorDzreyev** [comment]
Hi!
Ran everything except chapter_computational-performance/multiple-gpus-gluon.md and chapter_computational-performance/multiple-gpus.md

Has only one failure - chapter_natural-language-processing-applications/natural-language-inference-bert.md. Figuring out why.

**Comment by IgorDzreyev** [comment]
Something about:

UserWarning: Gradient of Parameter `dense76_bias` on context gpu(0) has not been updated by backward since last `step`. This could mean a bug in your model that made it only use a subset of the Parameters (Blocks) for this iteration. If you are intentionally only using a subset, call step with ignore_stale_grad=True to suppress this warning and skip updating of Parameters with stale gradient

**Comment by IgorDzreyev** [comment]
I rolled way back before my commits and this error is there...

**Pull request merged**
