### PR TITLE
try to fix #1326

### LINKED ISSUE #1326: bug for 17.1 or 17.2
image

http://preview.d2l.ai/d2l-en/master/chapter_generative-adversarial-networks/dcgan.html
http://preview.d2l.ai/d2l-en/master/chapter_generative-adversarial-networks/gan.html
I think there is a bug.

### PR DESCRIPTION
**Pull request by StevenJokes**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1327/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1327/

**Comment by StevenJokes** [comment]
I really need to sleep.😭PR tommorrow…

 
---Original---

**Comment by mli** [comment]
Job d2l-en/PR-1327/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1327/

**Comment by goldmermaid** [comment]
> Hey @StevenJokes , great catch. It seems that the 17.1 should have the legend flipped, rather than 17.2. Since:
> `metric.add(update_D(X, Z, net_D, net_G, loss, trainer_D), update_G(Z, net_D, net_G, loss, trainer_G), batch_size)`
> i.e., we first add the discriminator, then add the generator.
> 
> Can you reverse the current changes back, and modify 17.1? Thanks!

Hey @StevenJokes , could you make the modifications?

**Comment by StevenJokes** [comment]
I have modify it in https://github.com/d2l-ai/d2l-en/pull/1335/files. If you get it, maybe close this issue?

**Comment by goldmermaid** [comment]
Hi @StevenJokes , I have approved https://github.com/d2l-ai/d2l-en/pull/1335. Can you close this PR? Thanks!

**Comment by astonzhang** [comment]
https://github.com/d2l-ai/d2l-en/pull/1335 is merged. closing this pr.

**Pull request closed without merging**
