### PR TITLE
fix title

### LINKED ISSUE #974: Issue with plot titles in Section 18.6.1.6
In section [18.6.1.6. Standard Deviations](https://d2l.ai/chapter_appendix-mathematics-for-deep-learning/random-variables.html#standard-deviations) the three different plots with different probabilities show the same title i.e. `p>1/8`.

This should be resolved to `p>1/8, p=1/8,  p<1/8` for the 3 plots respectively.
We need to update `plt.title` for this. I'll send in a PR to fix this issue.

### PR DESCRIPTION
**Pull request by AnirudhDagar**
*Description of changes:*
This PR fixes #974 

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by bwerness** [comment]
should be "p = {p}" not "p > {p}"

**Comment by astonzhang** [comment]
@AnirudhDagar Thanks for fixing the problem. Could you request ppl (e.g., mu or I) to review your PR before it's merged? This might keep us aware of changes on the master branch.

**Comment by AnirudhDagar** [comment]
Sure @astonzhang , sorry for this. I merged this one because it was a very tiny change.

**Comment by AnirudhDagar** [comment]
yes @bwerness I noticed that later. It is fixed in master now.

**Pull request merged**
