### PR TITLE
Wouldn't say that Chainer is a successor of PyTorch

### PR DESCRIPTION
**Pull request by davidefiocco**
I deleted the string "its predecessor".

Chainer even came first (source: https://en.wikipedia.org/wiki/Chainer https://en.wikipedia.org/wiki/PyTorch).

### CODE REVIEW

**Comment by astonzhang** [comment]
This is a translation error: should be successor :)

**Comment by astonzhang** [comment]
@davidefiocco 

Thanks for your contributions to d2l-en (https://github.com/d2l-ai/d2l-en). Do you mind re-licensing all your contributions to us under the new license: MIT-0 for code and CC-BY-SA for text? This will allow more people to use d2l-en for free. All you need to do is replying to this message. Thanks.

Cheers,
Aston

**Comment by davidefiocco** [comment]
Sure.

**Comment by astonzhang** [comment]
Thanks!

**Pull request merged**
