### PR TITLE
typos fix

### PR DESCRIPTION
**Pull request by vfdev-5**
- Replaced `` -> "" in formulae
- Figure 10.X -> Figure 11.X

### CODE REVIEW

**Comment by zackchase** [comment]
I believe these changes are wrong. In LaTeX, including inside \textrm{....}, opening quotes need to be typeset with backticks (``).

**Comment by vfdev-5** [comment]
@zackchase I see what you mean. Yes, these changes are wrong, however currently with backticks (``) it is badly rendered : 
Screen Shot 2019-04-10 at 08 32 23

**Comment by zackchase** [comment]
Can you be more specific @vfdev-5 --- (we have multiple target formats). Is it badly rendered in GitHub, in HTML, in Jupyter, or in PDF?

**Comment by vfdev-5** [comment]
@zackchase sorry, it is badly rendered in HTML: https://d2l.ai/chapter_natural-language-processing/word2vec.html

**Comment by astonzhang** [comment]
Let us prioritize rendering on pdf. We'll try to make it render well on html later.

**Comment by vfdev-5** [comment]
Well, in pdf quotes look a bit strange too:
Screen Shot 2019-04-12 at 11 36 21
 
And there is still an issue with Figure numbers...

**Comment by astonzhang** [comment]
Thanks!

**Pull request merged**
