### PR TITLE
Update transformer.md

### PR DESCRIPTION
**Pull request by 315930399**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1508/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1508/

**Comment by astonzhang** [comment]
@AnirudhDagar , please take a look at @315930399 's  post at https://github.com/d2l-ai/d2l-en/issues/1484. Thanks

**Comment by mli** [comment]
Job d2l-en/PR-1508/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1508/

**Review by AnirudhDagar — APPROVED** [review]
Though this is not related to the problem with #1484, Thanks a tonne Yue for the correction! 
cc @ypandya

**Pull request merged**
