### PR TITLE
fix tf discussions tab pooling

### PR DESCRIPTION
**Pull request by AnirudhDagar**
*Description of changes:*
fix tf discussions tab in Pooling

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@AnirudhDagar Thanks but maybe squash your other tiny PRs into one?

**Comment by AnirudhDagar** [comment]
@terrytangyuan actually I made the changes from github itself. Otherwise would have sent a single PR for all.

**Comment by terrytangyuan** [comment]
Sure but you can check out your branch and add additional changes, especially given that your PRs are not merged yet? Just a suggestion though. No big deal.

**Comment by mli** [comment]
Job d2l-en/PR-1032/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1032/

**Comment by AnirudhDagar** [comment]
@terrytangyuan No problem. :) 
All changes now in. #1031

**Pull request closed without merging**
