### PR TITLE
Patch neg sampling

### PR DESCRIPTION
**Pull request by armingh2000**
*Description of changes:*
For negative sampling, the get_negatives function is not working properly. I changed the way it iterates through the dictionary. It works fine now.

@AnirudhDagar I made 2 commits here. The first is for .md file. The second one is after running `d2lbook build lib` and nothing else was changed thereafter. But there are no imports in torch.py file :|

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by AnirudhDagar** [comment]
This has been opened in favour of #1793.
No worries @armingh2000! Thanks for your contributions, I've made the change for rest of it.

**Review by AnirudhDagar — APPROVED** [review]
LGTM! Will wait for @astonzhang to merge and double check this.

**Comment by armingh2000** [comment]
@AnirudhDagar Thanks a lot for your patience. Can you say where did I get wrong? Just for further contributions, I am asking.

**Comment by mli** [comment]
Job d2l-en/PR-1796/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1796/

**Comment by AnirudhDagar** [comment]
@armingh2000 I'm not very sure why the `d2lbook build lib` command missed imports on your machine. Please make sure that the chapter preface was there in your local repo, since all the imports reside there.

If not, i think it is a windows only issue, you can go ahead and raise an issue on the [d2lbook](https://github.com/d2l-ai/d2l-book) github repo for that.

**Comment by armingh2000** [comment]
@AnirudhDagar yes I think you're right. I'll check that out. Thanks

**Comment by astonzhang** [comment]
@armingh2000  Great catch! I'll further simplify your proposed change as
`sampling_weights = [count**0.75 for count in counter.values()]`

**Comment by astonzhang** [comment]
@armingh2000, would you like to send another PR to replace your id with name in our acknowledgement:
https://github.com/d2l-ai/d2l-en/blob/master/chapter_preface/index.md

Thanks!

**Comment by armingh2000** [comment]
@astonzhang yes that would be better.  Should I change the related .md file and compile after that? If not, how can I change my id to my name?

**Comment by astonzhang** [comment]
> @astonzhang yes that would be better. Should I change the related .md file and compile after that? If not, how can I change my id to my name?
> Thanks

You may wish to refer to 19.6.1 https://d2l.ai/chapter_appendix-tools-for-deep-learning/contributing.html  on how to edit the md file (replacing id with name)

**Pull request merged**
