### PR TITLE
[Tensorflow] Adapted code sections for LSTM

### PR DESCRIPTION
**Pull request by PHOENIXFURY007**
Other than Concise Implementation & Training -Prediction, the rest code has been adapted in TF for LSTM.

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Thank you! Would you like to add the code for concise implementation as well? There are only a couple of code blocks left.

**Comment by floriandonhauser** [comment]
@terrytangyuan @PHOENIXFURY007 
I would like to offer my help to implement the concise implementation. If you would like me to do this part, just answer and I'd love to help.

**Comment by terrytangyuan** [comment]
I am fine as long as @PHOENIXFURY007 is not working on them. There's also https://github.com/d2l-ai/d2l-en/pull/1467 that I haven't got a chance to finish yet and feel free to pick it up as well.

**Comment by PHOENIXFURY007** [comment]
@floriandonhauser Yes , you can complete that part 😀

**Comment by terrytangyuan** [comment]
Superseded by https://github.com/d2l-ai/d2l-en/pull/1598

**Pull request closed without merging**
