### PR TITLE
bump to v 0.14.4

### PR DESCRIPTION
**Pull request by StevenJokes**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by StevenJokes** [comment]
If this fixs my problem, we should change version everytime we `d2lbook build`   the   `#@save` code.

**Comment by mli** [comment]
Job d2l-en/PR-1396/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1396/

**Comment by StevenJokes** [comment]
@AnirudhDagar 
Fix it ASAP

**Comment by StevenJokes** [comment]
@astonzhang 
Please fix it ASAP!
image

https://github.com/d2l-ai/d2l-en/issues/1374

**Comment by astonzhang** [comment]
We bump version only when we push to release branch and end users only refer to release branch. Master branch is only for developers so there's no need to bump version at the moment.

**Pull request closed without merging**
