### PR TITLE
[WIP] update the pytorch implementation with LazyAPI.

### PR DESCRIPTION
**Pull request by cheungdaven**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by astonzhang** [comment]
Is it complete or WIP? BTW, the CI needs some fix

**Comment by cheungdaven** [comment]
@d2l-bot rebuild

**Comment by astonzhang** [comment]
BTW, feel free to add [WIP] in the title if it'll take some time before the PR is ready for review :)

**Comment by astonzhang** [comment]
* If you are the only one who works on this PR, please rebase this PR to HEAD of master branch to incorporate the latest code changes, especially on CNNs (https://github.com/d2l-ai/d2l-en/pull/2106 and https://github.com/d2l-ai/d2l-en/pull/2105)
* After CI passes, please ensure all the evaluation results (e.g., training and eval plots) are decent. In case they are not, consider studying whether it's necessary to add forward pass similar to `self.net(torch.zeros(1,1,28,28))` right before the initialization, such as `self.net.apply(init_cnn_weights)` (see [LeNet class](http://preview.d2l.ai.s3-website-us-west-2.amazonaws.com/d2l-en/master/chapter_convolutional-neural-networks/lenet.html)). @AnirudhDagar  please share your insights if you find out if this is necessary for initializing lazy layers.

**Comment by cheungdaven** [comment]
@AnirudhDagar you can just review #2110.

**Pull request merged**
