### PR TITLE
add (not touching code having the tab '#@save')

### PR DESCRIPTION
**Pull request by StevenJokes**
learn from https://docs.dgl.ai/contribute.html

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1316/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1316/

**Comment by astonzhang** [comment]
Adding this is not necessary, though. E.g., some bug fixes are helpful.

**Comment by StevenJokes** [comment]
I don't think it's not necessary. I made a mistake to add code on github website.

**Comment by astonzhang** [comment]
Then it's reviewers' job to identify issues. We don't want to prevent the community to fix bugs in code.

**Comment by StevenJokes** [comment]
add "not touching the runnable #@save code at all"
#@save must need `d2lbook build lib`, so necessary to add it.

**Comment by mli** [comment]
Job d2l-en/PR-1316/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1316/

**Pull request closed without merging**
