### PR TITLE
[PyTorch] Add Kaggle CIFAR10

### PR DESCRIPTION
**Pull request by AnirudhDagar**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1545/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1545/

**Comment by mli** [comment]
Job d2l-en/PR-1545/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1545/

**Comment by astonzhang** [comment]
Thanks Anirudh. Happy Thanksgiving!

**Comment by AnirudhDagar** [comment]
Happy Thanksgiving to you too!! I just noticed a bug in this PR. Raising another one to fix the issue.

**Pull request merged**
