### PR TITLE
Update multivariable-calculus.md

### PR DESCRIPTION
**Pull request by EmilyOng**
*Description of changes:*
1. Fixed grammatical errors with sentence structure under 18.4.2 `Consider the again (18.4.5):`
2. Reworded partial derivatives section slightly in 18.4.1

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1818/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1818/

**Comment by mli** [comment]
Job d2l-en/PR-1818/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1818/

**Review by goldmermaid — APPROVED** [review]
LGTM! Thanks @EmilyOng !

**Comment by astonzhang** [comment]
@EmilyOng , thanks! Would you like to send another PR to replace your id with your name in our acknowledgement:
https://github.com/d2l-ai/d2l-en/blob/master/chapter_preface/index.md

**Pull request merged**
