### PR TITLE
[PyTorch] Add FCN

### PR DESCRIPTION
**Pull request by AnirudhDagar**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1566/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1566/

**Comment by mli** [comment]
Job d2l-en/PR-1566/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1566/

**Comment by AnirudhDagar** [comment]
Once #1568 #1569 are merged, I'll update this PR to make it compatible with the semantic segmentation dataset.

**Comment by mli** [comment]
Job d2l-en/PR-1566/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1566/

**Comment by mli** [comment]
Job d2l-en/PR-1566/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1566/

**Pull request merged**
