### PR TITLE
Try to help #1123,#1141,#1150 in softmax-regression-scratch.md

### PR DESCRIPTION
**Pull request by StevenJokes**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by StevenJokes** [comment]
please recheck.

**Comment by mli** [comment]
Python doesn't have `prod`, maybe we can use `math.prod` here

**Comment by StevenJokes** [comment]
Or we change it back to `y.numpy().size`?

**Comment by StevenJokes** [comment]
I can't figure out how to `d2lbook build lib`. Please change the required code for us first ,and tell me how to do it next time.

**Comment by astonzhang** [comment]
For all the usage of `d2l.evaluate_accuracy` and `d2l.train_ch3` (it uses d2l.evaluate_accuracy) throughout the book, `y` is a 1-D array, so `sum(y.shape)` gives the same value of `y.size` in mx, pt, and tf.

Since you mentioned that sum(y.shape) causes problems in  #1123,#1141,#1150, could you be a little more specific on why? Thanks.

**Comment by StevenJokes** [comment]
Can you explain the purpose of  "metric.add(accuracy(net(X), y), d2l.size(y))" in details for me?
It is hard to understand. A picture will be best.

**Pull request closed without merging**
