### PR TITLE
delete '2'

### PR DESCRIPTION
**Pull request by tayfununal**
There is a mistake that you probably forget (1/2) in the function.

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by tayfununal** [comment]
arrangement

**Comment by mli** [comment]
Job d2l-en/PR-1506/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1506/

**Comment by tayfununal** [comment]
This is true

**Comment by mli** [comment]
Job d2l-en/PR-1506/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1506/

**Review by goldmermaid — APPROVED** [review]
Math proofread! LGTM

Great catch and thanks for contribution @tayfununal !

**Pull request merged**
