### PR TITLE
Necessary to read Using Jupyter to new users.+URL

### PR DESCRIPTION
**Pull request by StevenJokes**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1101/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1101/

**Comment by mli** [comment]
Job d2l-en/PR-1101/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1101/

**Comment by astonzhang** [comment]
We'll revise this section while avoiding forward reference, which is not friendly to readers.

**Comment by StevenJokes** [comment]
ok, thanks

**Pull request closed without merging**
