### PR TITLE
Typo fixes and punctuation recommendation

### PR DESCRIPTION
**Pull request by edgarroman**
Additionally, changed 'plagiarising[sic]' to 'leveraging'.  The connotation of plagiarism is to take someone's work and claim it is your own.  While leveraging is to use something existing to maximum advantage.  I believe this is the intent of the sentence.

### CODE REVIEW

**Comment by astonzhang** [comment]
Thanks!

**Comment by astonzhang** [comment]
@edgarroman 

Thanks for your contributions to d2l-en (https://github.com/d2l-ai/d2l-en). Do you mind re-licensing all your contributions to us under the new license: MIT-0 for code and CC-BY-SA for text? This will allow more people to use d2l-en for free. All you need to do is replying to this message. Thanks.

Cheers,
Aston

**Comment by edgarroman** [comment]
Sure.

**Comment by astonzhang** [comment]
Thanks!

**Pull request merged**
