### PR TITLE
simplify lang model dataset

### PR DESCRIPTION
**Pull request by mli**
*Description of changes:*

removed the n-gram part, which will be moved to near work2vec 

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1850/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1850/

**Comment by mli** [comment]
Job d2l-en/PR-1850/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1850/

**Comment by astonzhang** [comment]
TODO: fix dependency of the change in the sequence data iterator.

**Comment by mli** [comment]
Job d2l-en/PR-1850/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1850/

**Pull request merged**
