### PR TITLE
Update probability.md: correct typo for 1000 rolls using np.random.multinomial

### PR DESCRIPTION
**Pull request by adgerson**
Correct typo for 1000 rolls of die using np.random.multinomial

### CODE REVIEW

**Comment by astonzhang** [comment]
Thanks for the fix!
Do you mind re-licensing all your d2l-en contributions to us under the new license: MIT-0 for code and CC-BY-SA for text? This will allow more people to use d2l-en for free. All you need to do is replying to this message. Thanks.

**Comment by adgerson** [comment]
Yes re-license all d2l-en contributions to the new license: MIT-0 for code and CC-BY-SA for text.

**Comment by astonzhang** [comment]
Thanks!

**Comment by astonzhang** [comment]
Besides, please email your GitHub ID, name, and mailing address to d2lbook.en@gmail.com. 
We'll mail a hard copy of D2L to you once it's printed out :)

**Comment by adgerson** [comment]
Thank you so much!

- Adam -

**Pull request merged**
