### PR TITLE
Aws updated

### PR DESCRIPTION
**Pull request by NRauschmayr**
I updated the chapter "Run on AWS", with details about Sagemaker andDLAMIs.

We currently update these instruction in all repositories:
https://github.com/mli/gluon-crash-course/pull/23
https://github.com/mli/new-docs/pull/27

### CODE REVIEW

**Comment by astonzhang** [comment]
Thanks. Currently we still wish to keep the original tutorial. For SageMaker, we may consider using it to demo code; thus, can you send this pull request to the contrib directory for the moment?

**Comment by astonzhang** [comment]
At the moment, we'd like to keep the original contents on aws. We may update it later.
Can you resolve the conflicts in the pr? Thanks.

**Comment by NRauschmayr** [comment]
I resolved the merge conflicts and updated the image paths.

**Comment by astonzhang** [comment]
Thanks. Can you change contrib/run-on-aws/aws.md to contrib/appendix/use-sagemaker.md and remove contrib/run-on-aws/use_ec2.md ?

**Comment by NRauschmayr** [comment]
I moved the images and modified the image references. Can we merge?

**Comment by astonzhang** [comment]
Thanks! As noted earlier, could you move images to `contrib/img/` instead of `contrib/chapter_appendix/img`? Then you need to refer the image with `caption`. All the images in the other chapters are referred in the same way, and we'd like to be consistent.

**Pull request merged**
