### PR TITLE
[TF] Densenet

### PR DESCRIPTION
**Pull request by abhinavsp0730**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1040/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1040/

**Comment by terrytangyuan** [comment]
@astonzhang It's actually merged from this PR. The confusing is caused by the commits that are not squashed before merging the PR.

**Comment by astonzhang** [comment]
Agree, let's squash commits when merging PR if it's from a single contributor.

**Comment by abhinavsp0730** [comment]
Hey, @astonzhang would you please describe ? I see some more comments in my mail but not able to see in the github.

**Pull request merged**
