### PR TITLE
fix featrue typo in chapter_modern-convolutional-neural-networks/alex…

### PR DESCRIPTION
**Pull request by RichyChen**
…net.md

*Description of changes:*
 I am reading the <Dive into deep learning> book, and find a typo in the "Deep Convolutional Neural Networks (AlexNet)".
    The original text is : 
      Interestingly in the lowest layers of the network, the model learned featrue extractors that resembled some traditional filters.

     I think it should be "feature extractors".

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by astonzhang** [comment]
Thanks!

**Comment by RichyChen** [comment]
OK. However, I find another typo in https://d2l.ai/chapter_convolutional-neural-networks/padding-and-strides.html 

> 
In some cases, we want to reduce the resolution drastically if say we find our original input resolution to be _unweildy_. Strides can help in these instances.
> 
I think it should be **unwieldy**.

**Comment by astonzhang** [comment]
Thanks. Can you send another PR?

**Comment by RichyChen** [comment]
Sorry, maybe another unproper expression on the same page  https://d2l.ai/chapter_convolutional-neural-networks/padding-and-strides.html#id1
"For any two-dimensional array X, when the kernels size is odd and the number of padding rows and columns on all sides are the same, producing **an output with _the have_ the same height and width as the input**"
It should be **an output with the same height and width as the input** .

**Comment by RichyChen** [comment]
Sure, I'll send.

**Pull request merged**
