### PR TITLE
Correct some typos in Preface and Notation

### PR DESCRIPTION
**Pull request by MucsanyiBalint**
I have corrected minor typos in the Preface section. Regarding the "blue skies" adjective, according to the Cambridge Dictionary, the "blue-sky" term is preferred.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1817/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1817/

**Comment by mli** [comment]
Job d2l-en/PR-1817/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1817/

**Comment by MucsanyiBalint** [comment]
Thank you for the feedback! Shall I create a new PR without the "blue-sky" modification, or is the commit of @zackchase sufficient to be able to merge the PR?

**Comment by mli** [comment]
Job d2l-en/PR-1817/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1817/

**Comment by mli** [comment]
Job d2l-en/PR-1817/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1817/

**Comment by astonzhang** [comment]
@MucsanyiBalint  Thanks! Could you send another PR to replace your ID with your name in our acknowledgement:
https://github.com/d2l-ai/d2l-en/blob/master/chapter_preface/index.md

**Comment by MucsanyiBalint** [comment]
@astonzhang Yes, thank you!

**Pull request merged**
