### PR TITLE
fix discussions tab

### PR DESCRIPTION
**Pull request by AnirudhDagar**
*Description of changes:*
This PR fixes the discussions tab link for TensorFlow in Chapter LeNet 

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1031/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1031/

**Comment by AnirudhDagar** [comment]
@terrytangyuan We can merge this once the CI is done.

**Comment by terrytangyuan** [comment]
Thanks!

**Comment by mli** [comment]
Job d2l-en/PR-1031/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1031/

**Comment by mli** [comment]
Job d2l-en/PR-1031/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1031/

**Pull request merged**
