### PR TITLE
delete space

### PR DESCRIPTION
**Pull request by StevenJokes**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1234/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1234/

**Comment by terrytangyuan** [comment]
Could you squash your tiny changes in a single PR?

**Comment by astonzhang** [comment]
Let's focus on something bigger than such purely cosmetic changes :)

**Comment by StevenJokes** [comment]
I have tried to squash your tiny changes in a single PR#1111.
Then I found the time delay is too long, and if there is some problem, `reset` is so inconvient.

**Comment by StevenJokes** [comment]
I suggest a vscode extension named Trailing Spaces. Then @astonzhang will get all extra spaces highlighted.

**Comment by astonzhang** [comment]
Nonetheless, I'm merging this pr for this time.

**Pull request merged**
