### PR TITLE
[WIP] switch to lazy api

### PR DESCRIPTION
**Pull request by mli**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
done chapter 1-5

**Comment by astonzhang** [comment]
While our CI is being upgraded without evaluation, just a headsup that LazyBatchNorm2d is in torch==1.9.0 (ci server with cu10.1 limits torch<=1.8.1)

**Comment by AnirudhDagar** [comment]
I was going through the documentation and right now PyTorch has no support for Lazy recurrent layers. Should we wait until the lazy module layers are stable and are fully supported across layers in PyTorch?

**Comment by AnirudhDagar** [comment]
@d2l-bot please rebuild this! :)

**Comment by AnirudhDagar** [comment]
> I was going through the documentation and right now PyTorch has no support for Lazy recurrent layers. Should we wait until the lazy module layers are stable and are fully supported across layers in PyTorch?

I noticed that PyTorch warns about the lazy layers since they are experimental and their API is not stable, is it ok to show those warnings in the book @mli?

**Comment by mli** [comment]
It should be fine, I think this warning should be removed by Pytorch later

**Comment by AnirudhDagar** [comment]
Yes maybe they will remove it by 1.12 release, but till then if we make a new release the users will see this warning which is not ideal. Btw is this still in WIP?

**Comment by AnirudhDagar** [comment]
@d2l-bot please rebuild!

**Pull request merged**
