### PR TITLE
Update distributions.md #1631

### PR DESCRIPTION
**Pull request by particle1331**
*Description of changes:*

Originally PR #1631. 
> Edited the first sentence of "While this result is not simple, the means and variances are. If X∼Binomial(n,p) , then" out. I also included an explanation for why this result should be immediately true.
> 
> Edited latex code in (18.8.7) Exponential Family. Changed
> \mathbf{\eta} to \boldsymbol{\eta}.
> Also, replaced
> \big{(} ... \big{)}
> with
> \left( ... \right).
> 
> Comment on the text:
> The notation mixes \cdot with \top... It's confusing whether \cdot is used as multiplication or as dot product since it's not clear what shapes T(x) and h(x) are.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by particle1331** [comment]
Hi @goldmermaid, trying out if it works. Also, I'm not sure how/why `d2l.bib` was modified. Perhaps you can skip accepting the commit for this particular file. I only meant to change `distributions.md`.

**Comment by mli** [comment]
Job d2l-en/PR-1652/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1652/

**Comment by mli** [comment]
Job d2l-en/PR-1652/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1652/

**Comment by goldmermaid** [comment]
Looks great to me! Thanks for being such a dedicated contributor @particle1331

**Pull request merged**
