### PR TITLE
fix typo in git documentation

### PR DESCRIPTION
**Pull request by dchoi77**
In 3.3.2, the following statement should be removed:
Since data is often used as a variable name, we will replace it with the pseudonym gdata (adding the first letter of Gluon), to differentiate the imported data module from a variable we might define.

It was used in an old version and gdata is not used at all in the section.

### CODE REVIEW

**Comment by astonzhang** [comment]
Thanks. Can you break change proposals into different PRs? Or, can you submit new change proposals in new PRs? It would be less convenient to review/comment/merge when many change proposals are in the same PR.

**Comment by dchoi77** [comment]
I am sorry to make change proposals into one PR. I just followed the section 15.6 of your book. When I select "New pull request", I could see "Create pull request" only at the first time. After the second change proposal, I could not see the green button "Create pull request". I simply put a comment to each change proposal. I think that's why all the proposals were merged. 

I am not good at using github. Could you let me know how to make separate PRs?

**Comment by astonzhang** [comment]
Click a .md file on this GitHub repo, such as 
https://github.com/d2l-ai/d2l-en/blob/master/chapter_attention-mechanism/seq2seq-attention.md

Click the pencil icon (Edit this file) on the top right, make edits.

At the bottom, add commit information, opt for
"Create a new branch for this commit and start a pull request. " (use a different branch name every time)

**Comment by astonzhang** [comment]
I saw that you opened a bunch of separate PRs. If they cover the change proposals of this PR, do you want to close this PR?

**Comment by dchoi77** [comment]
Thank you very much for letting me know how to make separate PRs, Dr. Zhang. I closed this PR as you requested.

**Pull request closed without merging**
