### PR TITLE
fix the tf bug in transformer.

### PR DESCRIPTION
**Pull request by cheungdaven**
*Description of changes:*

The flag training=True should be set, otherwise the model will not be trained.

The performance of tf is worse
By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by astonzhang** [comment]
@AnirudhDagar Since you had worked on this earlier, could you take a look first?

**Comment by astonzhang** [comment]
> _Description of changes:_
> 
> By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

Could you add brief explanations of the fix? Thanks

**Comment by cheungdaven** [comment]
@d2l-bot please rebuild

**Comment by cheungdaven** [comment]
> @cheungdaven the `seq2seq` section still doesn't work. Maybe it needs a change in the learning rate.

@AnirudhDagar This pr is only for the transformer issue, I did not check the seq2seq issue.

**Comment by AnirudhDagar** [comment]
I see, yes #2134 is definitely a bug that needs fixing but it is not the cause for the prediction issue in seq2seq.

Btw can you also add `training=False` here:
https://github.com/d2l-ai/d2l-en/blob/5aaf035bb728dbe731c435b36b3e7e195bdd78bc/chapter_recurrent-modern/seq2seq.md?plain=1#L284

https://github.com/d2l-ai/d2l-en/blob/5aaf035bb728dbe731c435b36b3e7e195bdd78bc/chapter_recurrent-modern/seq2seq.md?plain=1#L454

**Review by AnirudhDagar — APPROVED** [review]
Got it, thanks!

**Comment by astonzhang** [comment]
Thanks for the fix!

**Pull request merged**
