### PR TITLE
Add white background for all .svg for better visibility in dark mode

### PR DESCRIPTION
**Pull request by Melanol**
Was hard to see in dark mode, had to turn off for images, mostly because everything dark becomes invisible on transparent background.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1998/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1998/

**Comment by mli** [comment]
Job d2l-en/PR-1998/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1998/

**Comment by Melanol** [comment]
The website does not render backgrounds. Had to add white squares.

**Comment by astonzhang** [comment]
We are weighing adopting dark mode in the future so we'll keep transparent background :) Thanks.

**Pull request closed without merging**
