### PR TITLE
Fix: typo

### PR DESCRIPTION
**Pull request by atishaygarg**
Line 750: imaging -> imagine

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by astonzhang** [comment]
@atishaygarg thanks! Would you like to send another PR to replace your ID with name in our acknowledgement:
https://github.com/d2l-ai/d2l-en/blob/master/chapter_preface/index.md

**Comment by atishaygarg** [comment]
@astonzhang, it seems you've updated the same, thank you!

**Comment by astonzhang** [comment]
@atishaygarg I've added your GitHub ID. Would you like to replace it with your name? Thanks

**Comment by atishaygarg** [comment]
@astonzhang Yes, I would really appreciate that. Raising a pull request for the same. Thank you!

**Pull request merged**
