### PR TITLE
fix the broken download link for movielens dataset

### PR DESCRIPTION
**Pull request by cheungdaven**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by astonzhang** [comment]
Thanks. Can you run `d2lbook build lib` to save it into the d2l lib?

**Comment by astonzhang** [comment]
@AnirudhDagar we'll need this fix for 0.17.5, just FYI

**Comment by cheungdaven** [comment]
> Thanks. Can you run `d2lbook build lib` to save it into the d2l lib?

should not it be done automatically during compilation?

**Comment by astonzhang** [comment]
> > Thanks. Can you run `d2lbook build lib` to save it into the d2l lib?
> 
> should not it be done automatically during compilation?

As part of changes to the source code in the repo, changes to d2l lib should be submitted by developers. In other words, developers run `d2lbook build lib` and include changes to d2l lib in the same PR.

**Comment by AnirudhDagar** [comment]
> should not it be done automatically during compilation?
I was also thinking the same, some developers do not follow the d2lbook build lib process (or sometimes have an older version of d2lbook) and end up with different diffs.

**Pull request merged**
