### PR TITLE
Bump version to 1.0.0-alpha1

### PR DESCRIPTION
**Pull request by AnirudhDagar**
Prepare for patch release to fix colab bug in #2254.

### CODE REVIEW

**Comment by AnirudhDagar** [comment]
No need for version upgrade, this is a hotfix, so closing this.

**Comment by gab-chen** [comment]
@AnirudhDagar Thanks for applying the fix!

How do I use the fixed version? I ran the line "from d2l import torch as d2l" at a official pytorch notebook.
The same "ModuleNotFoundError" still occurred. 

I tried installing the the new 1.0.0-alpha1, but it does not exist. 
image

**Comment by AnirudhDagar** [comment]
@gab-chen we have not uploaded the new version on PyPI yet. There will be a bump in the d2l version (also upload to pypi) and a new release next week, and only then will the problem be solved.

@astonzhang I'm reopening this PR since we will bump the version soon, might as well just merge this.

**Comment by astonzhang** [comment]
> @gab-chen we have not uploaded the new version on PyPI yet. There will be a bump in the d2l version (also upload to pypi) and a new release next week, and only then will the problem be solved.
> 
> Till then, maybe you can just use `!pip install git+https://github.com/d2l-ai/d2l-en.git`
> 
> @astonzhang I'm reopening this PR since we will bump the version soon, might as well just merge this.

Let's bump the version once it's ready for release.

**Pull request merged**
