### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by PHOENIXFURY007**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1624/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1624/

**Comment by PHOENIXFURY007** [comment]
Do I close this PR now?

**Comment by mli** [comment]
Job d2l-en/PR-1624/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1624/

**Review by AnirudhDagar — APPROVED** [review]
Thanks!

**Pull request merged**
