### PR TITLE
[TF] Chapter 3 - Linear Neural Networks

### PR DESCRIPTION
**Pull request by terrytangyuan**
*Description of changes:* [TF] Chapter 3 - Linear Neural Networks

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
@mli Build failed with `AttributeError: module 'd2l.mxnet' has no attribute 'Timer'`. Looks like we are missing a few methods in `d2l/*.py` that are present in master branch. I can add methods missing in `d2l/tensorflow.py` but I guess the other methods for PyTorch and MXNet should be fixed separately. Otherwise there will be merge conflicts when we merge back to master. 

Why is the CI executing MXNet tabs though?

**Comment by terrytangyuan** [comment]
Actually when I run `d2lbook build lib`, all saved Python functions in `d2l/*.py` get updated. Should I just push all the updated `d2l/*.py`?

**Comment by terrytangyuan** [comment]
@mli I pushed all the generated files (including mxnet/pytorch) in the last commit https://github.com/d2l-ai/d2l-en/pull/943/commits/76675e70b23a04c86afaf6192f9f745a11960f3e in order to get CI happy. We can deal with conflicts when we merge back to master (master branch serves as source of truth so it should be fairly easy to resolve them).

**Comment by smolix** [comment]
@terrytangyuan - did you use the d2l tensorflow module? There are different modules for each framework. mxnet shouldn't be executed when you run the tf CI.

**Comment by terrytangyuan** [comment]
@smolix Yes, I did use the d2l tensorflow module. Not sure why mxnet was executed. Probably need to look into it separately but no worries now.

**Pull request merged**
