### PR TITLE
add 'requests'

### PR DESCRIPTION
**Pull request by StevenJokes**
*Description of changes:*

To avoid https://discuss.d2l.ai/t/installation/24/3 happen again.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by StevenJokes** [comment]
image
It isn't included in `pip install d2l -U`

**Comment by StevenJokes** [comment]
Do we need to include all packages in `d2l/` `mxnet.py` \`torch.py` \`tensorflow.py` library that need to be imported?

**Comment by StevenJokes** [comment]
Have we made sure these to be installed? I think now we didn't.
image

**Comment by StevenJokes** [comment]
https://github.com/d2l-ai/d2l-en/issues/1374 
fix it ASAP

**Comment by astonzhang** [comment]
https://github.com/d2l-ai/d2l-en/issues/1374#issuecomment-676779269

**Comment by StevenJokes** [comment]
To avoid pytorch https://discuss.d2l.ai/t/installation/24/3 happen again.
Or we just add 'requests'?

**Pull request closed without merging**
