### PR TITLE
[WIP] [TF] Add section on naive bayes

### PR DESCRIPTION
**Pull request by terrytangyuan**
*Description of changes:* Left some TODOs though that will addressed later when I get a chance.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1261/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1261/

**Comment by mli** [comment]
Job d2l-en/PR-1261/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1261/

**Comment by terrytangyuan** [comment]
@astonzhang Could we merge this first and I'll have to allocate some time to finish the TODOs later? This will avoid potential conflicts.

**Comment by astonzhang** [comment]
Sure, please fix TODOs later

**Pull request merged**
