### PR TITLE
[Do not merge] Test py3.8 for all the book, all frameworks

### PR DESCRIPTION
**Pull request by astonzhang**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1636/9 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1636/

**Comment by astonzhang** [comment]
Note that py3.8 requirement also triggers upgrade of ndformat, which causes ipynb -> rst to fail in some notebooks. We'll require nbformat <= 5.0.7 in d2lbook.

**Comment by mli** [comment]
Job d2l-en/PR-1636/10 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1636/

**Comment by mli** [comment]
Job d2l-en/PR-1636/11 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1636/

**Pull request closed without merging**
