### PR TITLE
Qrcode for Chapter 9 and 10

### PR DESCRIPTION
**Pull request by goldmermaid**
Add QR code as students starting asking question on the forum.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1440/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1440/

**Comment by astonzhang** [comment]
We will add it before the next release.

**Comment by goldmermaid** [comment]
No problem. Let me know when the content will be ready and we can reopen the PR.

**Comment by StevenJokess** [comment]
@goldmermaid 
I tried to add three units' discuss URL before...
The reason I messed around was your too slow actions and no any reply and offer to me.
3 days ago, I was angry by my uncles' words that I was playing at home three months.
That moment I really want to die...
Now I was reported, but you should know you need to be quicker to catch my paces and give me anything that I can see hope for my life.
I really want to help you, but you just left me alone and let me down.

**Pull request closed without merging**
