### PR TITLE
[vol2-xdl] Add section 3 for the xdl chapter

### PR DESCRIPTION
**Pull request by cheungdaven**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by cheungdaven** [comment]
@d2l-bot please rebuild

**Comment by cheungdaven** [comment]
@astonzhang  the error is related to your commits to d2lbook, do you know how to fix that?

**Comment by astonzhang** [comment]
Can you pull my recent commits from d2l-en/master? Specifically, https://github.com/d2l-ai/d2l-en/commit/02f3d88745faa93fff30c96402b1bddba68cf5da

**Comment by cheungdaven** [comment]
> Can you pull my recent commits from d2l-en/master? Specifically, [02f3d88](https://github.com/d2l-ai/d2l-en/commit/02f3d88745faa93fff30c96402b1bddba68cf5da)

It is still not working even with the commit you mentioned. I guess the latest d2lbook version is not used in the compilation. @astonzhang

**Comment by cheungdaven** [comment]
@d2l-bot please rebuild

**Pull request merged**
