### PR TITLE
more straight website

### PR DESCRIPTION
**Pull request by StevenJokes**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1377/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1377/

**Comment by mli** [comment]
Job d2l-en/PR-1377/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1377/

**Comment by astonzhang** [comment]
Adding external links can be risky (e.g., URLs may change without notifying us). We only add those that are absolutely necessary. Most of terms are searchable online and quite straightforward.

**Comment by StevenJokes** [comment]
OK. I got.

**Pull request closed without merging**
