### PR TITLE
fix gbk problem: #1065

### PR DESCRIPTION
**Pull request by StevenJokes**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by StevenJokes** [comment]
Why it works in my computer?

**Comment by StevenJokes** [comment]
I think it maybe has relation about operation system?

**Comment by StevenJokes** [comment]
Maybe we need to use Chinese version to avoid this problem?

**Comment by mli** [comment]
Job d2l-en/PR-1230/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1230/

**Comment by astonzhang** [comment]
Sorry, I don't think this *solves* any issue.

**Comment by StevenJokes** [comment]
It really works in my win10..

**Comment by StevenJokes** [comment]
The original version: https://github.com/d2l-ai/d2l-en/issues/1065.

**Comment by astonzhang** [comment]
Since this doesn't solve the problem, closing the pr

**Pull request closed without merging**
