### PR TITLE
add tensorflow and add illustration for d2l-en directory

### PR DESCRIPTION
**Pull request by StevenJokes**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1232/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1232/

**Comment by astonzhang** [comment]
Can you resolve conflicting files?

**Comment by StevenJokes** [comment]
I can. But I have no right to do it. 2am now. Maybe give me member, and I will fix it tomorrow.

**Comment by astonzhang** [comment]
You can resolve conflicts by rebasing this branch to master.

**Comment by StevenJokes** [comment]
I find the way to do it on github website. Is it `rebase`?

**Comment by mli** [comment]
Job d2l-en/PR-1232/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1232/

**Comment by StevenJokes** [comment]
It isn't `rebase`. But I still  think using a new branch to PR is a good habit to separate some small changes. 
For you, you can freely choose which one of PRs can be merged. 
For me, I can protect my `master` branch to keep same with your `master` branch.

**Comment by mli** [comment]
Job d2l-en/PR-1232/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1232/

**Pull request merged**
