### PR TITLE
Add authors on the frontpage

### PR DESCRIPTION
**Pull request by mli**
Hi @cheungdaven, @goldmermaid, @bwerness 

Thank you so much for contributing to d2l. As you are the co-author of at least one chapter, I'd like to have your names on the frontpage to highlight your contributions.

Please have a look if your personal information is correct. (@cheungdaven I didn't find a photo of you..)

Here is how the updated frontpage looks like

image

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by cheungdaven** [comment]
Hi Dr. Li,

Thank you very much.

My personal information is correct.  I attached my photo.

Best regards,
Shuai Zhang

**Comment by mli** [comment]
@cheungdaven  I didn't find the attached image

**Comment by goldmermaid** [comment]
Looks fantastic!! My pleasure to be the co-author :) 

Thank you, all!

**Comment by cheungdaven** [comment]
Hi Dr. @mli, I replied with my email  so the attached file might be lost. I just made a link for the photo. [photo](https://1drv.ms/u/s!AjPKhcGRzFUo7S-9mAvMo_TQK60n?e=5rRIXg). 
Thank you very much.

**Comment by mli** [comment]
updated @vanzytay

image

**Comment by mli** [comment]
the latest version

image

merging this PR now. please feel free to send PR to update your personal info

**Pull request merged**
