### PR TITLE
[do not merge] speedup ssd training: reduce epochs

### PR DESCRIPTION
**Pull request by AnirudhDagar**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by astonzhang** [comment]
Thanks. Have you tested in multiple runs to check randomness?

**Comment by mli** [comment]
Job d2l-en/PR-1634/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1634/

**Comment by mli** [comment]
Job d2l-en/PR-1634/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1634/

**Comment by mli** [comment]
Job d2l-en/PR-1634/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1634/

**Pull request closed without merging**
