### PR TITLE
[TF] Bump tensorflow and tensorflow-probability versions

### PR DESCRIPTION
**Pull request by terrytangyuan**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1808/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1808/

**Comment by astonzhang** [comment]
We need to test all the notebooks when changing libraries. Can you add 
`d2lbook clear`
right after this line 
https://github.com/d2l-ai/d2l-en/blob/master/Jenkinsfile#L22
to clear the evaluated notebooks?

After CI passes, you may remove that line before we merge this PR.

**Comment by terrytangyuan** [comment]
Sounds good. Doing that now.

**Comment by terrytangyuan** [comment]
Seems like there's timeout if we clear all the evaluated notebooks. Should I remove that line now so that it will re-evaluate the ones that have not been evaluated before?

**Comment by astonzhang** [comment]
> Seems like there's timeout if we clear all the evaluated notebooks. Should I remove that line now so that it will re-evaluate the ones that have not been evaluated before? I doubt that it's an issue with the new version of TF.

When you remove that line, it will re-evaluate only those failed notebooks if there's no new change in the master branch.
Can you send an issue to TF?

**Comment by terrytangyuan** [comment]
I am unclear what the issue is yet as the error is only related to timeout without anything specific. Let me try re-running it.

**Comment by terrytangyuan** [comment]
Still seeing `TimeoutError: Cell execution timed out`. @astonzhang Do you know what the current timeout is?

**Comment by astonzhang** [comment]
> Still seeing `TimeoutError: Cell execution timed out`. @astonzhang Do you know what the current timeout is?

Likely need to upgrade our CI, which takes time. For now just leave this issue to me. Thanks!

**Pull request closed without merging**
