### PR TITLE
Attention Fixes

### PR DESCRIPTION
**Pull request by goldmermaid**
Fix MLPAttention typos

### CODE REVIEW

**Comment by astonzhang** [comment]
Can you rebase to master HEAD to pass the ci?

**Comment by mli** [comment]
Job d2l-en/PR-1269/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1269/

**Comment by astonzhang** [comment]
Is this PR still wip?

**Comment by astonzhang** [comment]
Thanks. Next time please run `d2lbook build lib` to sync functions marked with @save to the d2l lib.

**Comment by goldmermaid** [comment]
Of course!

**Pull request merged**
