### PR TITLE
BLD: Bump r0.17 python support version 3.9

### PR DESCRIPTION
**Pull request by AnirudhDagar**
Follow up to #2231 for r0.17 brach.

### CODE REVIEW

**Comment by astonzhang** [comment]
It;s in https://github.com/d2l-ai/d2l-en/pull/2231/commits/20410aa03f6be1fa3410e05a4204e30cb9358e2d

**Comment by AnirudhDagar** [comment]
Yes but this is for r0.17 branch. I rebuilt it again for python 3.9 and updated the requirements.

**Comment by astonzhang** [comment]
Thanks. Could you propagate this change to all the translation repos?

**Comment by AnirudhDagar** [comment]
Yes, of course will do that!

**Comment by astonzhang** [comment]
Thanks. On d2l-zh, besides evaluation from scratch, just assign me to review it

**Pull request merged**
