### PR TITLE
[PyTorch ] Switch to torchvision nightly build

### PR DESCRIPTION
**Pull request by AnirudhDagar**
*Description of changes:*
 This is a temporary change to incorporate and use native `torchvision.io` instead of `PIL` in semantic segmentation dataset section as mentioned in #1567. We'll switch back to the stable releases as soon as the next torch/torchvision versions are out.
This will also fix issues with `PIL.Image` errors in #1566.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1568/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1568/

**Comment by mli** [comment]
Job d2l-en/PR-1568/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1568/

**Comment by astonzhang** [comment]
Since nightly versions keep updating, which may introduce bugs, can we fix a nightly build version, say a nightly version of some date? Then CI will always installs the same nightly version of that date, rather than always the latest version. 
Besides, all files depends on the version change. Thus we need to test all files before merging.

**Comment by AnirudhDagar** [comment]
@astonzhang that makes sense, fixed it to the date 19/12/2020 in my last commit.

**Comment by mli** [comment]
Job d2l-en/PR-1568/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1568/

**Pull request merged**
