### PR TITLE
revert all d2l alias before evaluation

### PR DESCRIPTION
**Pull request by mli**
*Description of changes:*

For all alias such as `d2l.ones`, `d2l.reshape`, we will convert them to the framework native operators before evaluation. 

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1153/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1153/

**Comment by astonzhang** [comment]
one risk for replacing d2l.reshape to mxnet reshape is that it may increase number of characters in a line (we require each line of code has <=78 chars), which may cause undesirable line breaks due to page width in pdf

**Comment by mli** [comment]
Job d2l-en/PR-1153/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1153/

**Comment by mli** [comment]
it should not happen, as we change from `d2l.reshape(a, ...)` to `a.reshape(...)`. but what could happen is from `d2l.ones` to `torch.ones`, which increase 2 chars.

**Pull request merged**
