### PR TITLE
updating torch.py - bug found

### PR DESCRIPTION
**Pull request by armingh2000**
In get_negatives function (line 2124), the sampling phase is wrong. It should iterate over keys in the counter dictionary, not the indexes. I changed this line:
`counter[i]**0.75 for i in range(len(counter))`
to this line:
`counter[key]**0.75 for key in counter.keys()`
It works correctly now.

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1793/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1793/

**Comment by armingh2000** [comment]
> 
> 
> Job d2l-en/PR-1793/1 is complete.
> Check the results at http://preview.d2l.ai/d2l-en/PR-1793/

It is not fixed in the book (the link you sent) yet.

**Review by AnirudhDagar — CHANGES_REQUESTED** [review]
Hi @armingh2000 thanks for the PR. Could you please make the change the change in the notebook itself?

Since these functions are automatically saved in the d2l [library](https://github.com/d2l-ai/d2l-en/tree/master/d2l). There is no need to manually change the `d2l/torch.py` file. You just need to generate that using `d2lbook build lib` once you have made the changes to the notebook (here it would be at `chapter_natural-language-processing-pretraining/word-embedding-dataset.md`). Lemme know if you need some help with this. You'll probably want to look at the contributing and development guidelines.

@astonzhang this is not only specific to PyTorch but is common to MXNet. We need to make the change for both the frameworks (fortunately we use `#@tab all` so a single change applies to both. Overall this fix LGTM, could you also take a look to be double sure? Thanks

**Comment by mli** [comment]
Job d2l-en/PR-1793/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1793/

**Comment by mli** [comment]
Job d2l-en/PR-1793/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1793/

**Comment by armingh2000** [comment]
Hi @AnirudhDagar . Thanks for the explanation. I reverted my changes on the library (torch.py) and made a new commit for .md file. I checked this link
[http://preview.d2l.ai/d2l-en/PR-1793/ ]()
and it is ok.

**Comment by AnirudhDagar** [comment]
Thanks @armingh2000 for the quick changes. You will still need to update the following lib files: `d2l/mxnet.py` and `d2l/torch.py`.

As I mentioned you can just run `d2lbook build lib` command to update the lib files and then commit those changes as well.
Note that you'll need [d2lbook](https://github.com/d2l-ai/d2l-book) library for that which can be installed like so :
```
pip install git+https://github.com/d2l-ai/d2l-book
```


Thanks again! :))

**Comment by armingh2000** [comment]
@AnirudhDagar I faced some problems running d2lbook build lib. It doesn't include imports. I think I am running it wrong

**Comment by AnirudhDagar** [comment]
@armingh2000 don't worry! 😄 

It's your first PR with d2l. I can understand it can be a bit overwhelming for a single line change.
Would you be sending another PR in favour of this? I can make the library changes committing to your branch. Or if you want I can open up a PR for you?

LMK!

**Pull request closed without merging**
