### PR TITLE
Linear from scratch

### PR DESCRIPTION
**Pull request by smolix**
*Description of changes:*

linear from scratch

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1865/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1865/

**Comment by mli** [comment]
Job d2l-en/PR-1865/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1865/

**Comment by mli** [comment]
Job d2l-en/PR-1865/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1865/

**Comment by smolix** [comment]
Merging to avoid conflicts going forward (this PR was green, then went orange again due to intersecting changes).

**Pull request merged**
