### PR TITLE
Update softmax-regression-concise.md

### PR DESCRIPTION
**Pull request by JoshB29**
The current version of the modified softmax function and text (equation 3.7.1)  is not clear. It is not clear how it helps with the overflow error that can happen explained earlier in the paragraph; even though this equation helps with not evaluating 𝑜𝑗 in the numerator, it still has to be evaluated in the sum taken in -log(∑𝑘exp(𝑜𝑘)).  It looks like that this section is trying to show Log-sum-exp trick explained here: https://timvieira.github.io/blog/post/2014/02/11/exp-normalize-trick/ (and briefly mentioned in the text), so that equation 3.7.1 should include the normalization.  I included the normalization in the proposed change, and text more clearly explaining what it is doing.

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1593/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1593/

**Review by JoshB29 — COMMENTED** [review]
I fixed a basic grammar/syntax issue in the proposed change

**Comment by mli** [comment]
Job d2l-en/PR-1593/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1593/

**Comment by JoshB29** [comment]
This looks correct to me!

**Comment by mli** [comment]
Job d2l-en/PR-1593/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1593/

**Comment by astonzhang** [comment]
Thanks! It's indeed much clearer. I'll make some further minor edits after merging this PR.

**Comment by astonzhang** [comment]
Could you send another PR to replace your GitHub ID with name in the acknowledgement:
https://github.com/d2l-ai/d2l-en/blob/master/chapter_preface/index.md

**Pull request merged**
