### PR TITLE
Update rnn-scratch.md

### PR DESCRIPTION
**Pull request by zhangjiekui**
bug fixed: transpose Y accordingly (because we have transposed X)

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1552/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1552/

**Review by terrytangyuan — APPROVED** [review]
Thanks! Is this bug being tracked anywhere yet? If so, could you link it in the description?

**Comment by astonzhang** [comment]
Thanks! I think it fixed #1349 !

**Comment by astonzhang** [comment]
Thanks! Could you send a PR to replace your github ID with your name in the acknowledgement: https://github.com/d2l-ai/d2l-en/blob/master/chapter_preface/index.md

**Pull request merged**
