### PR TITLE
[WIP] started added basic pytorch code to recommender systems of d2l.ai

### PR DESCRIPTION
**Pull request by divo12**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-2005/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-2005/

**Comment by divo12** [comment]
yeah it's fine

**Review by AnirudhDagar — COMMENTED** [review]
Hi @divo12, please let us know when the PR is ready. Thanks for initiating this :))

**Comment by KuanHaoHuang** [comment]
Hi @divo12, thanks for starting this PR.
I wish I can contribute PyTorch codes to the Recommender System chapters as well.
Do you have any tentative plan for this PR and the following timeline?
I'd like to know what and when I could contribute.
Thanks!

**Comment by divo-almighty** [comment]
Yeah sure
You can collaborate with me on this PR.I am also learning about Recommender systems and by the way I am learning I wish to contribute to D2L to help the future learners using pytorch :).Right now I don't have any tentative plans but we can make it together and whatever changes you will do,just update here

**Comment by divo12** [comment]
Yeah sure
You can collaborate with me on this PR.I am also learning about Recommender systems and by the way I am learning I wish to contribute to D2L to help the future learners using pytorch :).Right now I don't have any tentative plans but we can make it together and whatever changes you will do,just update here

**Comment by AnirudhDagar** [comment]
Hi @divo12 @KuanHaoHuang, thank you both for showing interest. I'll open an issue to track the progress on this chapter. Since this PR has no code at the moment, I guess we can start from scratch. Feel free to comment on that issue so that we can work together.

@divo12 I'll close this PR for now, in case you have some updates feel free to open it again and commit the changes. Thanks!

Please feel free to ping me/ tag me in case there are any questions or blockers.

**Pull request closed without merging**
