### PR TITLE
[TF] Add section on information theory

### PR DESCRIPTION
**Pull request by terrytangyuan**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1252/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1252/

**Comment by AnirudhDagar** [comment]
@terrytangyuan PTAL [here](http://preview.d2l.ai/d2l-en/PR-1252/chapter_appendix-mathematics-for-deep-learning/information-theory.html#example)

KL Divergence is inconsistent with MX/PT

**Comment by terrytangyuan** [comment]
Thanks. Yeah there are inconsistency among a couple others as well. I’ll look into them.

**Comment by terrytangyuan** [comment]
Fixed now.

**Comment by mli** [comment]
Job d2l-en/PR-1252/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1252/

**Pull request merged**
