### PR TITLE
Fix a typo in softmax-regression.md

### PR DESCRIPTION
**Pull request by trungha-ngx**

### CODE REVIEW

**Comment by astonzhang** [comment]
@trungha-ngx 

Thanks for your contributions to d2l-en (https://github.com/d2l-ai/d2l-en). Do you mind re-licensing all your contributions to us under the new license: MIT-0 for code and CC-BY-SA for text? This will allow more people to use d2l-en for free. All you need to do is replying to this message. Thanks.

**Comment by trungha-ngx** [comment]
> 
> 
> @trungha-ngx
> 
> Thanks for your contributions to d2l-en (https://github.com/d2l-ai/d2l-en). Do you mind re-licensing all your contributions to us under the new license: MIT-0 for code and CC-BY-SA for text? This will allow more people to use d2l-en for free. All you need to do is replying to this message. Thanks.

Please, do!
Cheers.

**Comment by astonzhang** [comment]
You mean you do not mind, right?

**Comment by trungha-ngx** [comment]
No, I do not mind.

**Comment by astonzhang** [comment]
Thanks!

**Pull request merged**
