### PR TITLE
pytorch: add img classification

### PR DESCRIPTION
**Pull request by AnirudhDagar**

### CODE REVIEW

**Comment by AnirudhDagar** [comment]
@mli I think the CI is missing the torchvision module. It is almost like a goto when working with vision in PyTorch. I hope you can add that to the CI. Once that is done, all checks should pass.

**Comment by AnirudhDagar** [comment]
There appears to be a confict here. I'll just rebase this and update this PR.

**Comment by mli** [comment]
you can change the environment here

https://github.com/d2l-ai/d2l-en/blob/pytorch/Jenkinsfile#L25

**Comment by mli** [comment]
besides, i only enabled a few chapters so we can make the CI to be built fast. you can add more chapters once you done the linear chapter

https://github.com/d2l-ai/d2l-en/blob/pytorch/config.ini#L22

**Comment by AnirudhDagar** [comment]
Cool! I've sent separate PRs to update config.ini and Jenkins file.

**Comment by AnirudhDagar** [comment]
@mli I think the tests should be re-run here. It still says missing torchvison module.

**Comment by AnirudhDagar** [comment]
closing this and replacing the pr by #869

**Pull request closed without merging**
