### PR TITLE
add Contribute content

### PR DESCRIPTION
**Pull request by StevenJokes**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1375/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1375/

**Comment by mli** [comment]
Job d2l-en/PR-1375/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1375/

**Comment by astonzhang** [comment]
We already have contribute section.

**Comment by StevenJokes** [comment]
Yes, we do. But, maybe we should mention it earily a little bit to make readers to know the section to aviod the issue like https://github.com/d2l-ai/d2l-en/issues/1373.

**Pull request closed without merging**
