### PR TITLE
Update machine-translation-and-dataset.md

### PR DESCRIPTION
**Pull request by tcmyxc**
*Description of changes:*
这个问题是因为电脑的编码问题产生的，如果地区和位置设置为中国，默认编码是gbk，此时程序是无法正常运行的，报错如下：

> UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 33: illegal multibyte sequence

需要加上编码格式，之后程序可以正常运行。

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1880/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1880/

**Comment by smolix** [comment]
Good defensive programming.

**Comment by astonzhang** [comment]
@tcmyxc Thanks! Can you send another PR to replace your id with your name in our acknowledgement:
https://github.com/d2l-ai/d2l-en/blob/master/chapter_preface/index.md

**Comment by tcmyxc** [comment]
> @tcmyxc Thanks! Can you send another PR to replace your id with your name in our acknowledgement:
> https://github.com/d2l-ai/d2l-en/blob/master/chapter_preface/index.md

OK, thank you!

**Pull request merged**
