### PR TITLE
Update torch.eig method and add missing import in d2l/torch.py

### PR DESCRIPTION
**Pull request by Okroshiashvili**
Add missing Numpy import in d2l/torch.py, remove an extra letter, and set a parameter in ```torch.eig``` to show corresponding eigenvectors.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by Okroshiashvili** [comment]
@mli What's wrong with TensorFlow?

**Comment by AnirudhDagar** [comment]
@Okroshiashvili It has been fixed in PR #1042

**Comment by AnirudhDagar** [comment]
Also @Okroshiashvili thanks for the fix in `eigendecomposition` can you force push to re-run the CI now or just make a new PR if you want.

**Comment by Okroshiashvili** [comment]
@AnirudhDagar you're welcome. Let me make new PR in a moment.

**Comment by mli** [comment]
Job d2l-en/PR-1041/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1041/

**Pull request merged**
