### PR TITLE
[PyTorch] Add MiniBatch SGD

### PR DESCRIPTION
**Pull request by AnirudhDagar**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by AnirudhDagar** [comment]
This PR required the bug fix made in `evaluate_loss`  by #1245 
Hence had to merge that before creating this PR.

**Comment by mli** [comment]
Job d2l-en/PR-1247/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1247/

**Comment by mli** [comment]
Job d2l-en/PR-1247/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1247/

**Comment by mli** [comment]
Job d2l-en/PR-1247/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1247/

**Pull request merged**
