### PR TITLE
Update linear-algebra.md

### PR DESCRIPTION
**Pull request by dowobeha**
Distinguish between zero-based indexing (in the code examples) and one-based indexing (in the math example).

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1791/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1791/

**Comment by dowobeha** [comment]
In the preview, the reference to the equation number doesn't appear to come through correctly. This is one of my first commits, could someone please advise if I made a syntax error? Thanks!

**Comment by astonzhang** [comment]
> In the preview, the reference to the equation number doesn't appear to come through correctly. This is one of my first commits, could someone please advise if I made a syntax error? Thanks!

should be :eqref:

**Comment by zackchase** [comment]
This is an important point and perhaps should be made explicitly here but this version is too verbose. Do not merge.

**Comment by smolix** [comment]
I manually integrated the spirit of the edits into #1877 - since we were in the process of a complete rewrite of the chapter, the fix didn't work in its original place any longer (even the subsection names changed). **Many thanks** for sending us the PR.

**Pull request closed without merging**
