### PR TITLE
[PyTorch] Bump pytorch to latest stable release

### PR DESCRIPTION
**Pull request by AnirudhDagar**
*Description of changes:*
With the recent minor releases of torch 1.8.1 & torchvision 0.9.1, this PR bumps the CI to use the latest stable releases.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by astonzhang** [comment]
Thanks. After ci passes, please remove d2l clear and merge it

**Comment by mli** [comment]
Job d2l-en/PR-1697/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1697/

**Comment by mli** [comment]
Job d2l-en/PR-1697/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1697/

**Comment by mli** [comment]
Job d2l-en/PR-1697/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1697/

**Comment by AnirudhDagar** [comment]
@astonzhang this PR is ready now.

**Comment by astonzhang** [comment]
Thanks. If I'm not mistaken, CI failed earlier right?

**Comment by AnirudhDagar** [comment]
Yep, it did! But that was an issue with saving the downloaded dataset from `torchvision`. It is definitely not a `torch 1.8.1` & `torchvision 0.9.1` based issue.

**Comment by astonzhang** [comment]
oh, so everything just passed after re-running?

**Comment by AnirudhDagar** [comment]
Yeah, exactly!

**Comment by astonzhang** [comment]
Thanks! Let me re-run everything to ensure it passes again.

**Comment by AnirudhDagar** [comment]
Yeah, that's a good idea.

**Pull request merged**
