### PR TITLE
fix: Typos in Linear Neural Networks

### PR DESCRIPTION
**Pull request by EmilyOng**
*Description of changes:*
- Fixes typos/grammars

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by smolix** [comment]
Fixing the fix of the fix.

**Comment by mli** [comment]
Job d2l-en/PR-1867/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1867/

**Comment by mli** [comment]
Job d2l-en/PR-1867/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1867/

**Comment by mli** [comment]
Job d2l-en/PR-1867/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1867/

**Comment by mli** [comment]
Job d2l-en/PR-1867/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1867/

**Pull request merged**
