### PR TITLE
PR in our repo, easy to create pr.

### PR DESCRIPTION
**Pull request by StevenJokes**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by astonzhang** [comment]
I think going to user's fork is also quite convenient. Besides, it confuses readers when using figures showing different account names.

**Comment by StevenJokes** [comment]
I think it is inconvient for new users, because they don't know how to go to their fork ..

**Comment by astonzhang** [comment]
Would you like to close this PR?

**Comment by astonzhang** [comment]
See https://github.com/d2l-ai/d2l-en/pull/1238#issuecomment-673014764

**Pull request closed without merging**
