### PR TITLE
[PyTorch] Add Momentum

### PR DESCRIPTION
**Pull request by AnirudhDagar**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1256/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1256/

**Comment by astonzhang** [comment]
Can you resolve conflict?

**Comment by AnirudhDagar** [comment]
I've resolved the conflicts @astonzhang but the CI has failed due to some other error.

**Comment by mli** [comment]
Job d2l-en/PR-1256/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1256/

**Comment by astonzhang** [comment]
Fixed CI, now it passes.

**Pull request merged**
