### PR TITLE
 add `git branch`

### PR DESCRIPTION
**Pull request by StevenJokes**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by astonzhang** [comment]
https://github.com/d2l-ai/d2l-en/pull/1233#issuecomment-663718562

**Comment by astonzhang** [comment]
Again, it's not a book for git operations. For now we want to keep this part minimal and focus more on deep learning. Can you close this PR?

**Comment by StevenJokes** [comment]
But for developer, a new branch will protect `master`.

**Comment by astonzhang** [comment]
This section is for external contributors where they will just send PR from *their* master to *d2l/master*

**Comment by StevenJokes** [comment]
But I still think using a new branch to PR is a good habit to separate some small changes.
For you, you can freely choose which one of PRs can be merged.
For me, I can protect my master branch to keep same with your master branch.

**Comment by astonzhang** [comment]
Thanks. Using multiple branches is of course more efficient, but for advanced Git users. Our tutorial for tools is targeting new users to keep such non-DL content minimal (we don't want to write another book about Git, about Jupyter notebooks, about AWS, about Colab, about SageMaker). For new users to separate small changes, the current section has introduced how to "edit" directly on Github repo. However, managing multiple branches is usually not so straightforward to new users and explaining it clearly demands more illustrations (more than this PR), such as to introduce how Git works. Since there are plenty of excellent online Git resources, we don't need to repeat them in the main text. One idea is to point new users to official Git documentation in the exercises so they can dive into it if interested. So I am going to close this PR and merge & revise your other PR on the exercise.

**Pull request closed without merging**
