### PR TITLE
Update gd.md

### PR DESCRIPTION
**Pull request by e-tony**
Fixed `eta` in function argument.

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1750/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1750/

**Comment by e-tony** [comment]
Or is this a conscious decision to simplify the code?

**Comment by astonzhang** [comment]
> Or is this a conscious decision to simplify the code?

Yes, we just made it simple

**Comment by astonzhang** [comment]
Thanks anyway!

**Pull request closed without merging**
