### PR TITLE
updating method parameters

### PR DESCRIPTION
**Pull request by gopalakrishna-r**
changing method parameter from "test_feature" to "test_features"

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1982/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1982/

**Comment by gopalakrishna-r** [comment]
Hi,

The link "http://preview.d2l.ai/d2l-en/PR-1982/" just forwards me to the d2l.ai home page. I'm not able to view any build results. 

Please let me know if the PR needs to be created on a branch different than the "release" one. The master branch doesn't have as many pages as the release one and is way behind it when comes to commits.

**Comment by astonzhang** [comment]
Thanks. Can you send your PR to r0.17 branch?

**Comment by AnirudhDagar** [comment]
Let's wait for the CI before merging this.

**Comment by AnirudhDagar** [comment]
@d2l-bot please rebuild!

**Review by AnirudhDagar — APPROVED** [review]
Thanks for the fix! LGTM

**Comment by astonzhang** [comment]
@gopalakrishna-r  Thanks! Could you send another PR to replace your github id with your name in our acknowledgement?
https://github.com/d2l-ai/d2l-en/blob/master/chapter_preface/index.md

**Pull request merged**
