### PR TITLE
Clarify miniconda installation steps

### PR DESCRIPTION
**Pull request by vcavallo**
*Description of changes:*

I've noticed a few comments indicating some subtle confusion over Python versions related to the Miniconda installation. I suspect some readers are hastily copy-pasting the installation commands, which could lead to problems.
I updated the language a bit to reinforce that the commands are examples and that readers should visit the Miniconda website and pay attention to their own system details.

---

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1685/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1685/

**Comment by mli** [comment]
Job d2l-en/PR-1685/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1685/

**Comment by astonzhang** [comment]
Thanks! I'm merging it and will further revise the text based on this PR. 
Could you send another PR to replace your id with name on our acknowledgement section: https://github.com/d2l-ai/d2l-en/blob/master/chapter_preface/index.md

**Comment by vcavallo** [comment]
> Thanks! I'm merging it and will further revise the text based on this PR.
> Could you send another PR to replace your id with name on our acknowledgement section: https://github.com/d2l-ai/d2l-en/blob/master/chapter_preface/index.md

https://github.com/d2l-ai/d2l-en/pull/1686 :+1:

**Pull request merged**
