### PR TITLE
update names of team members

### PR DESCRIPTION
**Pull request by duythanhvn**
*Description of changes:* These are the names of the people on my team, I update their names instead of GitHub names.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1521/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1521/

**Comment by astonzhang** [comment]
Thanks.

@tiepvupsu
@minhduc0711
@cuongvng
@nguyenhoa93

Can you please confirm your names are correct?

**Comment by cuongvng** [comment]
Yes, thank you!

**Comment by minhduc0711** [comment]
@astonzhang yup it's correct

**Comment by tiepvupsu** [comment]
@astonzhang My name is correct. Thanks.

**Comment by nguyenhoa93** [comment]
My name is correct as well. Thank you!

**Review by AnirudhDagar — APPROVED** [review]

**Pull request merged**
