### PR TITLE
Bug fixes for 0.17post1 release

### PR DESCRIPTION
**Pull request by AnirudhDagar**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1984/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1984/

**Comment by astonzhang** [comment]
Please rebase to HEAD of the r0.17 branch. Thanks!

**Comment by AnirudhDagar** [comment]
This should be ready now.

**Comment by mli** [comment]
Job d2l-en/PR-1984/7 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1984/

**Pull request merged**
