### PR TITLE
Adding a gentler background to attention and motivate the use of the …

### PR DESCRIPTION
**Pull request by frankieliu**
…word attention

*Issue #, if available:*  NA

*Description of changes:* Added a background paragraph referring Bahdanau's paper and the motivation behind idea of attention.  I would like to add a few more motivational figures from the paper, please let me know if going in this direction is acceptable.  Thanks.

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by smolix** [comment]
Hi Frankie, indeed, the attention chapter needs a lot of attention. We haven't incorporated the content from the ICML'19 tutorial that Aston and I gave yet. Our plan is to use this to structure the content. Just that we haven't had time yet to do it yet since there are other chapters, too, that need a lot of work.

**Comment by frankieliu** [comment]
Thanks Alex, do you guys need any help in writing parts of this?  Just wondering how I can contribute.  Thanks. -frankie

**Comment by astonzhang** [comment]
Thanks for your contributor to D2L! To review your changes, could you:

1) Save your changes;
2) Delete your forked yourusername/d2l-en repo, re-fork d2l-ai/d2l-en to yourusername/d2l-en
3) Commit your changes to yourusername/d2l-en, re-submit your PR.
4) Then you may close this PR so we can review your new PR

**Comment by astonzhang** [comment]
Closing this PR for now. You could re-submit this PR by following the instructions above. Thanks!

**Pull request closed without merging**
