### PR TITLE
Fix typos and grammatical errors

### PR DESCRIPTION
**Pull request by MucsanyiBalint**
By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1832/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1832/

**Comment by mli** [comment]
Job d2l-en/PR-1832/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1832/

**Comment by mli** [comment]
Job d2l-en/PR-1832/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1832/

**Comment by MucsanyiBalint** [comment]
Most of the problems were resolved by the latest changes. I am closing this PR.

**Pull request closed without merging**
