### PR TITLE
delete #@tab all, shifting to mxnet only.fix #1116

### LINKED ISSUE #1116: [pytorch]4.4 has a bug in preview version. PR in #1117
bug
fix it in 8th cell:
https://github.com/StevenJokes/D2L_enread/blob/39eed9751b195d14da685c8374e992045b2fc19e/Ch04_MP/4-4-new.ipynb

### PR DESCRIPTION
**Pull request by StevenJokes**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1117/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1117/

**Comment by StevenJokes** [comment]
It works.
image
image

**Comment by astonzhang** [comment]
Actually we do want to show the results of `features[:2].T, poly_features[:2, :], labels[:2]` across all the frameworks.

**Comment by StevenJokes** [comment]
Please look issue #1116 carefully, then you will get that pytorch's version  will have a bug!

**Comment by mli** [comment]
Job d2l-en/PR-1117/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1117/

**Pull request closed without merging**
