### PR TITLE
docker install

### PR DESCRIPTION
**Pull request by alukovenko**
Added files and instructions to provide fast Docker installations.

### CODE REVIEW

**Comment by astonzhang** [comment]
Thanks for providing the Docker option. As we do have Dockerfile in d2l-zh (https://github.com/d2l-ai/d2l-zh/blob/master/Dockerfile), we may port that into d2l-en later.

**Comment by astonzhang** [comment]
@alukovenko 

Thanks for your contributions to d2l-en (https://github.com/d2l-ai/d2l-en). Do you mind re-licensing all your contributions to us under the new license: MIT-0 for code and CC-BY-SA for text? This will allow more people to use d2l-en for free. All you need to do is replying to this message. Thanks.

Cheers,
Aston

**Comment by alukovenko** [comment]
I believe that this pull request was reverted. Anyway, I don't mind re-licensing this contribution.

**Comment by astonzhang** [comment]
Thanks!

**Pull request merged**
