### PR TITLE
added additional basic matrix properties

### PR DESCRIPTION
**Pull request by kirk86**
Adding basic matrix properties with accompanying code examples!

### CODE REVIEW

**Comment by astonzhang** [comment]
Thanks. However, currently we plan to include only properties that will be used or referenced in subsequent chapters.

**Comment by astonzhang** [comment]
Would you like to move your added properties to the contrib/chapter_crashcourse/linear-algebra.md directory? We may move it back to the book if it will be used in the future :)

**Comment by kirk86** [comment]
@astonzhang
Hi Aston,
sure no problem at all. Would you like me to do another pull request?

**Comment by astonzhang** [comment]
yes, you may close this one and send a new pr

**Comment by kirk86** [comment]
@astonzhang ok. Thanks!

**Pull request closed without merging**
