### PR TITLE
TF2 code for attention mechanisms chapter (Chapter 10)

### PR DESCRIPTION
**Pull request by biswajitsahoo1111**
At present, only section 10.1 contains relevant TF code. This pull request adds TF code for section 10.2. Subsequently TF code for all other sections of chapter 10 will be added. Running code (TF-2.4.0 compatible) for all sections of chapter 10 can be found [here](https://github.com/biswajitsahoo1111/D2L_Attention_Mechanisms_in_TF). Gradually I will create pull requests for other sections. 

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1756/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1756/

**Review by terrytangyuan — APPROVED** [review]
Thank you!

**Comment by astonzhang** [comment]
@biswajitsahoo1111 Thanks. Could you send another pr to replace your id with name in our acknowledgement:
https://github.com/d2l-ai/d2l-en/blob/master/chapter_preface/index.md

**Comment by biswajitsahoo1111** [comment]
@astonzhang Thanks. Done.

**Pull request merged**
