### PR TITLE
Update lenet.md

### PR DESCRIPTION
**Pull request by MatteoFerrara**
In LeNet-5 there 3 convolutional layers (C1, C3 and C5). See: https://en.wikipedia.org/wiki/LeNet#Structure[5]_[6]

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1503/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1503/

**Comment by astonzhang** [comment]
In the paper, there are 2 convs and 3 FCs: See fig2 in http://yann.lecun.com/exdb/publis/pdf/lecun-98.pdf

**Comment by MatteoFerrara** [comment]
Dear Aston Zhang,

 

in my opinion, in Fig. 2 the layer C5 is a convolutional layer as reported in the left column of pag. 8.

The neurons of C5 are fully connected to those of S4 only because the size of the kernels is equal to the size of S4 (120 kernels of size 16x5x5).

 

Best regards,

 

Matteo Ferrara 

 

------------------------------------

Matteo Ferrara, Ph.D.

Associate Professor

Department of computer science and engineering - DISI

University of Bologna – Italy

email:  <mailto:matteo.ferrara@unibo.it> matteo.ferrara@unibo.it
web:  <http://www.unibo.it/faculty/matteo.ferrara> http://www.unibo.it/faculty/matteo.ferrara

------------------------------------

______________________________________________________________________________

 Please consider the environment before printing this email.

______________________________________________________________________________

The information contained in this email message and its attachments is intended only for the private and confidential use of the recipient(s) named above, unless the sender expressly agrees otherwise. If the reader of this message is not the intended recipient and/or you have received this email in error, you must take no action based on the information in this email and you are hereby notified that any dissemination, misuse, copying, or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately by email and delete the original message.

 

Da: Aston Zhang <notifications@github.com> 
Inviato: giovedì 29 ottobre 2020 18:58
A: d2l-ai/d2l-en <d2l-en@noreply.github.com>
Cc: MatteoFerrara <matteo.ferrara@unibo.it>; Author <author@noreply.github.com>
Oggetto: Re: [d2l-ai/d2l-en] Update lenet.md (#1503)

 

In the paper, there are 2 convs and 3 FCs: See fig2 in http://yann.lecun.com/exdb/publis/pdf/lecun-98.pdf

**Comment by astonzhang** [comment]
Thanks. 

In left column of Page 8:

"Layer C5 is a conv layer with 120 feature maps. Each unit is connected to a 5x5 neighborhood on all 16 of S4's feature maps."

It means 16*5*5 = 400 units is mapped to 120 units. This can be done via

either

400 x 120 FC layer (input: 400 units, output: 120 units)

or

120 x 16 x 5 x 5 Conv layer (input: 16 5x5 feature maps, output: 120 1x1 feature maps)

The above two are equivalent.

See code output in this section:

conv0 output shape:  (1, 6, 28, 28)
pool0 output shape:  (1, 6, 14, 14)
conv1 output shape:  (1, 16, 10, 10)
pool1 output shape:  (1, 16, 5, 5)
dense0 output shape:         (1, 120)
dense1 output shape:         (1, 84)
dense2 output shape:         (1, 10)

**Comment by MatteoFerrara** [comment]
Dear Aston Zhang,

 

I agree with you but, as reported by the authors in the left column of pag. 8, if the input size of LeNet-5 increases not all C5 neurons will be connected to the previous layer S4.

For this reason, in my opinion, would be better to present C5 as convolutional layer instead of fully-connected, although in this case they are the same thing.

 

Regards,

 

Matteo

 

------------------------------------

Matteo Ferrara, Ph.D.

Associate Professor

Department of computer science and engineering - DISI

University of Bologna – Italy

email:  <mailto:matteo.ferrara@unibo.it> matteo.ferrara@unibo.it
web:  <http://www.unibo.it/faculty/matteo.ferrara> http://www.unibo.it/faculty/matteo.ferrara

------------------------------------

______________________________________________________________________________

 Please consider the environment before printing this email.

______________________________________________________________________________

The information contained in this email message and its attachments is intended only for the private and confidential use of the recipient(s) named above, unless the sender expressly agrees otherwise. If the reader of this message is not the intended recipient and/or you have received this email in error, you must take no action based on the information in this email and you are hereby notified that any dissemination, misuse, copying, or disclosure of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately by email and delete the original message.

 

Da: Aston Zhang <notifications@github.com> 
Inviato: venerdì 30 ottobre 2020 19:58
A: d2l-ai/d2l-en <d2l-en@noreply.github.com>
Cc: MatteoFerrara <matteo.ferrara@unibo.it>; Author <author@noreply.github.com>
Oggetto: Re: [d2l-ai/d2l-en] Update lenet.md (#1503)

 

Thanks.

In left column of Page 8:

"Layer C5 is a conv layer with 120 feature maps. Each unit is connected to a 5x5 neighborhood on all 16 of S4's feature maps."

It means 1655 = 400 units is mapped to 120 units. This can be done via

either

400 x 120 FC layer (input: 400 units, output: 120 units)

or

120 x 16 x 5 x 5 Conv layer (input: 16 5x5 feature maps, output: 120 1x1 feature maps)

The above two are equivalent.

See code output in this section:

conv0 output shape: (1, 6, 28, 28)
pool0 output shape: (1, 6, 14, 14)
conv1 output shape: (1, 16, 10, 10)
pool1 output shape: (1, 16, 5, 5)
dense0 output shape: (1, 120)
dense1 output shape: (1, 84)
dense2 output shape: (1, 10)

**Comment by astonzhang** [comment]
Thanks! Throughout this book, we consistently refer to this step as "flatten then fully-connect". This is also what most recent papers use.

**Comment by mli** [comment]
Job d2l-en/PR-1503/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1503/

**Comment by astonzhang** [comment]
Closing it for now. Thanks.

**Pull request closed without merging**
