### PR TITLE
add the way to add new branch

### PR DESCRIPTION
**Pull request by StevenJokes**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1233/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1233/

**Comment by mli** [comment]
Job d2l-en/PR-1233/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1233/

**Comment by astonzhang** [comment]
We intend to keep this section minimal (d2l is not a book about git) enough to just get things done

**Comment by StevenJokes** [comment]
Yes, but I think having new branch is necessary. We should keep all PR is small which can be done only if we have lots of branch . A new branch based on master will protect master's branch. We can easily remove the branch if PR can't pass.  Compare with `reset`, `remove` branch is more convinent when we have lots of PR. Some advice..

**Comment by astonzhang** [comment]
Again, it's not a book for git operations. For now we want to keep this part minimal and focus more on deep learning. Can you close this PR?

**Comment by StevenJokes** [comment]
But I still think using a new branch to PR is a good habit to separate some small changes.
For you, you can freely choose which one of PRs can be merged.
For me, I can protect my master branch to keep same with your master branch.

**Comment by mli** [comment]
Job d2l-en/PR-1233/3 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1233/

**Comment by astonzhang** [comment]
Using multiple branches is of course more efficient, but for *advanced* Git users. Our tutorial for tools is targeting *new* users to **keep such non-DL content minimal**. For *new* users, to separate small changes the current section introduces how to "edit" directly on Github repo, however, managing multiple branches is usually not so straightforward to them and explaining it clearly demands more sections to introduce how Git works. There are plenty of online resources of Git and we don't want to be a book about Git.

**Comment by astonzhang** [comment]
See https://github.com/d2l-ai/d2l-en/pull/1238#issuecomment-673014764
I'm going to revise this edit.

**Pull request merged**
