### PR TITLE
[TF2] add GAN

### PR DESCRIPTION
**Pull request by StevenJokess**
loss_D 0.683, loss_G 0.683, 267.2 examples/sec
Check https://github.com/StevenJokess/d2l-en-read/blob/moreme/chapter-generative-adversarial-networks/gan-tf-ok/gan_tf6%20(3).ipynb

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1716/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1716/

**Comment by StevenJokess** [comment]
My discussion:
https://discuss.d2l.ai/t/generative-adversarial-networks/2534/2

**Comment by mli** [comment]
Job d2l-en/PR-1716/5 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1716/

**Comment by mli** [comment]
Job d2l-en/PR-1716/6 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1716/

**Comment by astonzhang** [comment]
https://discuss.d2l.ai/t/topic/2563

Again, please stop any inappropriate conduct on all channels of D2L. Since this is not the first violation of our code of conduct, we'll welcome you back once you learn how to behave properly and secure a job (this was already mentioned before). Good luck.

**Pull request closed without merging**
