### PR TITLE
Update seqrec.md

### PR DESCRIPTION
**Pull request by rootonchair**
*Description of changes:*
As the code above said L=3. Thank @minhduc0711 for spotting this

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1474/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1474/

**Comment by astonzhang** [comment]
@cheungdaven Do you prefer updating `L=3` to `L=5` in the code or this proposed change?

**Comment by cheungdaven** [comment]
Both should be fine as long as the descriptions in code and text are consistent.

**Comment by astonzhang** [comment]
Thanks! Maybe changing to L=5 is a better idea?

**Comment by cheungdaven** [comment]
@astonzhang  I agree. Maybe revise the code instead? @rootonchair

**Comment by rootonchair** [comment]
@cheungdaven , @astonzhang I have fixed L to 5 in the code

**Comment by mli** [comment]
Job d2l-en/PR-1474/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1474/

**Review by AnirudhDagar — APPROVED** [review]

**Pull request merged**
