### PR TITLE
fix momenta url

### PR DESCRIPTION
**Pull request by gkutiel**
Changed momenta URL from www.momenta.com to www.momenta.ai. The former is a leading designer while the later is an autonomous driving company.

### CODE REVIEW

**Comment by astonzhang** [comment]
Thanks!

**Comment by astonzhang** [comment]
@gkutiel 

Thanks for your contributions to d2l-en (https://github.com/d2l-ai/d2l-en). Do you mind re-licensing all your contributions to us under the new license: MIT-0 for code and CC-BY-SA for text? This will allow more people to use d2l-en for free. All you need to do is replying to this message. Thanks.

Cheers,
Aston

**Comment by gkutiel** [comment]
Sure, no problem.

**Comment by astonzhang** [comment]
Thanks!

**Pull request merged**
