### PR TITLE
fix(Sequence Models): steps should be counted after tau

### PR DESCRIPTION
**Pull request by mzz2017**
As the code shows, steps should be counted after tau.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1380/1 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1380/

**Comment by mzz2017** [comment]
The preview shows two weird graph outputs in the tf version however it works fine on my own computer.

**Comment by astonzhang** [comment]
Thanks for the fix! Recently I just made heavy revisions to this section, including improving the code for multistep-ahead prediction.

Does the current version look good to you?
http://preview.d2l.ai.s3-website-us-west-2.amazonaws.com/d2l-en/master/chapter_recurrent-neural-networks/sequence.html

If anything does not make sense to you, feel free to point it out :)

**Comment by mzz2017** [comment]
Looks good, thanks for your revisions.

**Pull request closed without merging**
