### PR TITLE
[Don't merge]Just Build PDF [PyTorch]

### PR DESCRIPTION
**Pull request by StevenJokess**
try to build PDF for PyTorch code.

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1705/2 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1705/

**Comment by mli** [comment]
Job d2l-en/PR-1705/4 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1705/

**Comment by StevenJokess** [comment]
d2lbook don't support pdf tab...

**Comment by astonzhang** [comment]
https://discuss.d2l.ai/t/topic/2563

Again, please stop any inappropriate conduct on all channels of D2L. Since this is not the first violation of our code of conduct, we'll welcome you back once you learn how to behave properly and secure a job (this was already mentioned before). Good luck.

**Comment by indigoviolet** [comment]
It seems like this is based on the suggestion by Rachel Hu [here](https://discuss.d2l.ai/t/is-it-possible-to-have-the-pdf-book-with-examples-displayed-using-pytorch/2426/2) to build a pdf with PyTorch code. However AFAICT, the generated pdf http://preview.d2l.ai/d2l-en/PR-1705/d2l-en.pdf does not appear to have PyTorch code in it.

**Pull request closed without merging**
