### PR TITLE
[do not merge] test code_format

### PR DESCRIPTION
**Pull request by astonzhang**
*Description of changes:*

By submitting this pull request, I confirm that you can use, modify,
copy, and redistribute this contribution, under the terms of your
choice.

### CODE REVIEW

**Comment by mli** [comment]
Job d2l-en/PR-1641/12 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1641/

**Comment by mli** [comment]
Job d2l-en/PR-1641/14 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1641/

**Comment by mli** [comment]
Job d2l-en/PR-1641/17 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1641/

**Comment by mli** [comment]
Job d2l-en/PR-1641/16 is complete. 
Check the results at http://preview.d2l.ai/d2l-en/PR-1641/

**Comment by astonzhang** [comment]
Updated minor style issues at https://github.com/d2l-ai/d2l-book/issues/26

**Pull request closed without merging**
